# -*- coding: utf-8 -*-
"""Exercício programação Recursiva.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mRdFVKk8ReWpP3l-vWNWl7bd4UCNAZ4p
"""

n = int(input("Entre com um número: "))

for h in range(1, n+1):

    num_caract = ((h) * 2) - 1

    loc_1 = h
    loc_2 = h

    for i in range(num_caract):

        if i == 0:
            print(' '*(h-1), end='')
            print('#', end='') 
            print(' '*(h-1))
            continue

        else:

            if i > h-1:
                loc_1 += 1
                loc_2 -= 1

            else:
                loc_1 -= 1 
                loc_2 += 1

            for j in range(num_caract):
                if j+1 == loc_1 or j+1 == loc_2:
                    print('#', end='')
                else:
                    print(' ', end='')
            print(end='\n')
    print(end='\n')